image: golang:1.19.1

build:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - GOOS=darwin GOARCH=arm64 go build -o mac-appdiff main.go
    - GOOS=linux GOARCH=amd64 go build -o linux-appdiff main.go
  artifacts:
    paths:
      - linux-appdiff
      - mac-appdiff
