name: Go package

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1

      - name: Build
        run: go build -o ./linux-appdiff -v
      
      - name: Archive appdiff binary for linux
        uses: actions/upload-artifact@v3
        with:
          name: linux-appdiff
          path: linux-appdiff

  build-macos:

    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1

      - name: Build
        run: go build -o ./macos-appdiff -v
      
      - name: Archive appdiff binary for macos
        uses: actions/upload-artifact@v3
        with:
          name: macos-appdiff
          path: macos-appdiff
